raw_sources_dir: data/raw_sources
test_sources_dir: data/test_sources
master_original_dir: data/master_original
splits_original_dir: data/splits_original
augmented_train_dir: data/augmented_train
use_external_test_set: true

valid_image_extensions:
  - .jpg
  - .jpeg
  - .png

classes:
  0: person
  1: helmet
  2: vest

split:
  train: 0.80
  val: 0.20
  test: 0.00

random_seed: 42
